---
language: php

php:
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

# This triggers builds to run on the new (faster) TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
    - "${HOME}/.composer/cache"

env:
  global:
    - PATH="${HOME}/bin:${PATH}"

matrix:
  allow_failures:
  - php: hhvm
  - php: 5.4
  - php: 5.3
  fast_finish: true

before_install:
  - npm set loglevel error
  - npm set progress false

install:
  - composer global require "dealerdirect/qa-tools:*"
  - npm install -g jsonlint

script:
  - find . -type f -name "*.json" -print0 | xargs -0 -n1 jsonlint -q
  - composer validate
  - travis_wait composer install --no-interaction --no-progress --no-scripts --no-suggest --optimize-autoloader --prefer-dist --verbose
  - ~/.composer/vendor/bin/parallel-lint ./src
  - ~/.composer/vendor/bin/security-checker -n security:check --end-point=http://security.sensiolabs.org/check_lock
  - ~/.composer/vendor/bin/phpcs --standard=psr2 src/

